CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++17
SRC = src
BIN = server

SOURCES = $(wildcard $(SRC)/*.cpp)
OBJECTS = $(SOURCES:.cpp=.o)

all: $(BIN)

$(BIN): $(SOURCES)
	$(CXX) $(CXXFLAGS) -o $@ $^

run: $(BIN)
	./$(BIN)

clean:
	rm -f $(BIN) *.o